// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB31hT_qynyMs8SKZva39boBQ6rq8Le564',
    appId: '1:1083567243287:web:e24e2cf23beeb4e5c25c52',
    messagingSenderId: '1083567243287',
    projectId: 'clone-reddi',
    authDomain: 'clone-reddi.firebaseapp.com',
    storageBucket: 'clone-reddi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsUZ5oOBuRWqicHK9YE5idMxNRM4e8Rek',
    appId: '1:1083567243287:android:20cd0c370c52e0b0c25c52',
    messagingSenderId: '1083567243287',
    projectId: 'clone-reddi',
    storageBucket: 'clone-reddi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfiz06QzMuSGzFGEDuGfQm10WODgoWLgY',
    appId: '1:1083567243287:ios:d92e7547f3391eefc25c52',
    messagingSenderId: '1083567243287',
    projectId: 'clone-reddi',
    storageBucket: 'clone-reddi.appspot.com',
    iosClientId: '1083567243287-nmkts5pfe8kkiemknmjtvep0cherfr57.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
